let employee = [
  {
    id: 1,
    first_name: "Denyse",
    email: "dbruins0@scribd.com",
    gender: "Female",
  },
  {
    id: 2,
    first_name: "Marius",
    email: "mosgodby1@berkeley.edu",
    gender: "Male",
  },
  { id: 3, first_name: "Duke", email: "dspada2@cisco.com", gender: "Male" },
  {
    id: 4,
    first_name: "Carmita",
    email: "cmacdaid3@guardian.co.uk",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Rina",
    email: "rmartyn4@altervista.org",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Caresa",
    email: "cphippard5@eventbrite.com",
    gender: "Female",
  },
  {
    id: 7,
    first_name: "Deck",
    email: "dmacpake6@issuu.com",
    gender: "Agender",
  },
  {
    id: 8,
    first_name: "Salmon",
    email: "stattershaw7@google.com",
    gender: "Male",
  },
  {
    id: 9,
    first_name: "Rachel",
    email: "rellinor8@ucla.edu",
    gender: "Female",
  },
  {
    id: 10,
    first_name: "Ursula",
    email: "utoombs9@hugedomains.com",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Dexter",
    email: "dleiversa@discuz.net",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Faydra",
    email: "felegoodb@nsw.gov.au",
    gender: "Female",
  },
  {
    id: 13,
    first_name: "Jasun",
    email: "jsleichtc@oracle.com",
    gender: "Male",
  },
  {
    id: 14,
    first_name: "Auberta",
    email: "aabramovitzd@live.com",
    gender: "Female",
  },
  { id: 15, first_name: "Margalit", email: "mcobone@g.co", gender: "Female" },
  {
    id: 16,
    first_name: "Marthe",
    email: "mdennidgef@spiegel.de",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Alecia",
    email: "acritchellg@technorati.com",
    gender: "Female",
  },
  {
    id: 18,
    first_name: "Burnard",
    email: "bbecarish@cyberchimps.com",
    gender: "Male",
  },
  {
    id: 19,
    first_name: "Berkley",
    email: "bliddiatti@who.int",
    gender: "Male",
  },
  {
    id: 20,
    first_name: "Hunter",
    email: "hsimcoxj@squarespace.com",
    gender: "Bigender",
  },
  {
    id: 21,
    first_name: "Sol",
    email: "sfeakek@infoseek.co.jp",
    gender: "Male",
  },
  {
    id: 22,
    first_name: "Janos",
    email: "jwicksl@chronoengine.com",
    gender: "Male",
  },
  { id: 23, first_name: "Hort", email: "hplaidm@sogou.com", gender: "Male" },
  {
    id: 24,
    first_name: "Gaby",
    email: "gstedelln@bravesites.com",
    gender: "Male",
  },
  {
    id: 25,
    first_name: "Traver",
    email: "tlightningo@sina.com.cn",
    gender: "Male",
  },
  {
    id: 26,
    first_name: "Emile",
    email: "eleitchep@cbslocal.com",
    gender: "Male",
  },
  {
    id: 27,
    first_name: "Hillier",
    email: "habilowitzq@symantec.com",
    gender: "Male",
  },
  {
    id: 28,
    first_name: "Rebeka",
    email: "rgooderridger@auda.org.au",
    gender: "Female",
  },
  {
    id: 29,
    first_name: "Webster",
    email: "wfuchers@foxnews.com",
    gender: "Male",
  },
  {
    id: 30,
    first_name: "Aline",
    email: "alisciardellit@weibo.com",
    gender: "Polygender",
  },
  {
    id: 31,
    first_name: "Faun",
    email: "fgauleru@jigsy.com",
    gender: "Bigender",
  },
  {
    id: 32,
    first_name: "Scotti",
    email: "sferneyv@yellowpages.com",
    gender: "Male",
  },
  {
    id: 33,
    first_name: "Euphemia",
    email: "erudgardw@issuu.com",
    gender: "Female",
  },
  {
    id: 34,
    first_name: "Penni",
    email: "pwhittingtonx@amazon.com",
    gender: "Female",
  },
  {
    id: 35,
    first_name: "Paolo",
    email: "pslefordy@sakura.ne.jp",
    gender: "Male",
  },
  {
    id: 36,
    first_name: "Agretha",
    email: "amapholmz@ifeng.com",
    gender: "Female",
  },
  {
    id: 37,
    first_name: "Benoit",
    email: "bflaxon10@sina.com.cn",
    gender: "Male",
  },
  {
    id: 38,
    first_name: "Mitchael",
    email: "mgormley11@gravatar.com",
    gender: "Male",
  },
  {
    id: 39,
    first_name: "Alexis",
    email: "afrayling12@adobe.com",
    gender: "Male",
  },
  {
    id: 40,
    first_name: "Christi",
    email: "cworral13@cmu.edu",
    gender: "Female",
  },
  {
    id: 41,
    first_name: "Sayer",
    email: "sstraw14@over-blog.com",
    gender: "Male",
  },
  {
    id: 42,
    first_name: "Justino",
    email: "jiacavone15@reuters.com",
    gender: "Male",
  },
  {
    id: 43,
    first_name: "Ardisj",
    email: "ayepiskopov16@sphinn.com",
    gender: "Female",
  },
  {
    id: 44,
    first_name: "Harri",
    email: "hluckwell17@cam.ac.uk",
    gender: "Female",
  },
  { id: 45, first_name: "Hallsy", email: "hburdoun18@epa.gov", gender: "Male" },
  {
    id: 46,
    first_name: "Roma",
    email: "rhove19@telegraph.co.uk",
    gender: "Male",
  },
  { id: 47, first_name: "Slade", email: "svalance1a@admin.ch", gender: "Male" },
  {
    id: 48,
    first_name: "Celestine",
    email: "ckonke1b@lulu.com",
    gender: "Female",
  },
  {
    id: 49,
    first_name: "Nickola",
    email: "ncrowcroft1c@addthis.com",
    gender: "Male",
  },
  {
    id: 50,
    first_name: "Cass",
    email: "ciannuzzelli1d@guardian.co.uk",
    gender: "Female",
  },
  {
    id: 51,
    first_name: "Hinda",
    email: "hbowne1e@chron.com",
    gender: "Female",
  },
  {
    id: 52,
    first_name: "Cynthy",
    email: "cgrigoriev1f@cbsnews.com",
    gender: "Female",
  },
  { id: 53, first_name: "Yvor", email: "ylassey1g@gmpg.org", gender: "Male" },
  {
    id: 54,
    first_name: "Julieta",
    email: "jknightly1h@phoca.cz",
    gender: "Female",
  },
  {
    id: 55,
    first_name: "Shayla",
    email: "swevell1i@ocn.ne.jp",
    gender: "Female",
  },
  {
    id: 56,
    first_name: "Florella",
    email: "fellin1j@themeforest.net",
    gender: "Female",
  },
  {
    id: 57,
    first_name: "Franz",
    email: "fmacneice1k@cornell.edu",
    gender: "Male",
  },
  { id: 58, first_name: "Bambie", email: "balu1l@narod.ru", gender: "Female" },
  { id: 59, first_name: "Nev", email: "nlambshine1m@xing.com", gender: "Male" },
  {
    id: 60,
    first_name: "Englebert",
    email: "eolenov1n@unicef.org",
    gender: "Male",
  },
  {
    id: 61,
    first_name: "Guido",
    email: "gruppel1o@google.com",
    gender: "Male",
  },
  {
    id: 62,
    first_name: "Isabelita",
    email: "imaingot1p@istockphoto.com",
    gender: "Bigender",
  },
  {
    id: 63,
    first_name: "Licha",
    email: "lhofner1q@vimeo.com",
    gender: "Bigender",
  },
  {
    id: 64,
    first_name: "Idalina",
    email: "ibourthoumieux1r@newyorker.com",
    gender: "Female",
  },
  {
    id: 65,
    first_name: "Berri",
    email: "bhallick1s@engadget.com",
    gender: "Female",
  },
  {
    id: 66,
    first_name: "Allen",
    email: "aleonida1t@scientificamerican.com",
    gender: "Male",
  },
  { id: 67, first_name: "Valle", email: "vboig1u@g.co", gender: "Male" },
  {
    id: 68,
    first_name: "Henrieta",
    email: "hdefreyne1v@bbb.org",
    gender: "Female",
  },
  {
    id: 69,
    first_name: "Munmro",
    email: "mlindmark1w@dagondesign.com",
    gender: "Male",
  },
  {
    id: 70,
    first_name: "Jesselyn",
    email: "jgreenhough1x@dedecms.com",
    gender: "Female",
  },
  {
    id: 71,
    first_name: "Hilde",
    email: "hcalderon1y@goodreads.com",
    gender: "Female",
  },
  {
    id: 72,
    first_name: "Karalee",
    email: "kteacy1z@alexa.com",
    gender: "Bigender",
  },
  {
    id: 73,
    first_name: "Charyl",
    email: "cdragon20@npr.org",
    gender: "Female",
  },
  {
    id: 74,
    first_name: "Yetta",
    email: "ystrivens21@miibeian.gov.cn",
    gender: "Female",
  },
  {
    id: 75,
    first_name: "Kelby",
    email: "kianne22@berkeley.edu",
    gender: "Male",
  },
  {
    id: 76,
    first_name: "Jamesy",
    email: "jnoddings23@topsy.com",
    gender: "Bigender",
  },
  { id: 77, first_name: "Andy", email: "acassam24@ask.com", gender: "Male" },
  {
    id: 78,
    first_name: "Coralie",
    email: "cbosward25@123-reg.co.uk",
    gender: "Female",
  },
  { id: 79, first_name: "Wake", email: "wpenas26@nyu.edu", gender: "Male" },
  {
    id: 80,
    first_name: "Schuyler",
    email: "schaplain27@gnu.org",
    gender: "Male",
  },
  {
    id: 81,
    first_name: "Forrest",
    email: "fbeuscher28@ocn.ne.jp",
    gender: "Male",
  },
  {
    id: 82,
    first_name: "Allie",
    email: "atonsley29@utexas.edu",
    gender: "Male",
  },
  {
    id: 83,
    first_name: "Rosita",
    email: "rcroker2a@meetup.com",
    gender: "Female",
  },
  { id: 84, first_name: "Alvie", email: "astarmer2b@youtu.be", gender: "Male" },
  {
    id: 85,
    first_name: "Etta",
    email: "evenes2c@wordpress.com",
    gender: "Female",
  },
  {
    id: 86,
    first_name: "Brittaney",
    email: "bdomaschke2d@live.com",
    gender: "Female",
  },
  {
    id: 87,
    first_name: "Kent",
    email: "kdaniaud2e@bloglovin.com",
    gender: "Male",
  },
  {
    id: 88,
    first_name: "Marie-ann",
    email: "mpear2f@state.tx.us",
    gender: "Female",
  },
  { id: 89, first_name: "Forrest", email: "fmuehler2g@un.org", gender: "Male" },
  { id: 90, first_name: "Murdock", email: "mdight2h@ftc.gov", gender: "Male" },
  { id: 91, first_name: "Inger", email: "iwilce2i@ucla.edu", gender: "Male" },
  {
    id: 92,
    first_name: "Alikee",
    email: "agaylor2j@networksolutions.com",
    gender: "Non-binary",
  },
  {
    id: 93,
    first_name: "Boot",
    email: "bmacgee2k@behance.net",
    gender: "Bigender",
  },
  {
    id: 94,
    first_name: "Minetta",
    email: "mgrimes2l@shop-pro.jp",
    gender: "Female",
  },
  {
    id: 95,
    first_name: "Greer",
    email: "gbielfelt2m@wsj.com",
    gender: "Female",
  },
  {
    id: 96,
    first_name: "Raina",
    email: "rkivlin2n@buzzfeed.com",
    gender: "Genderqueer",
  },
  {
    id: 97,
    first_name: "Bryant",
    email: "btabord2o@usatoday.com",
    gender: "Male",
  },
  {
    id: 98,
    first_name: "Ezra",
    email: "emckeown2p@zimbio.com",
    gender: "Male",
  },
  {
    id: 99,
    first_name: "Brigitta",
    email: "beltun2q@about.com",
    gender: "Female",
  },
  {
    id: 100,
    first_name: "Ardys",
    email: "aruthven2r@tinyurl.com",
    gender: "Genderqueer",
  },
];

function displayData() {
  let row = "";
  let i = 0;
  while (i < employee.length) {
    row =
      row +
      `<tr>    
                <td>${employee[i].id} </td>
                <td>${employee[i].first_name} </td>
                <td>${employee[i].email} </td>
       </tr>`;
    i++;
  }
  document.getElementById("srinu").innerHTML = row;
}
